// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_i_need_a_more_gold = "CgkIhaXbp9AHEAIQCg"; // <GPGSID>
        public const string achievement_experienced = "CgkIhaXbp9AHEAIQBg"; // <GPGSID>
        public const string achievement_cash_is_a_king = "CgkIhaXbp9AHEAIQCw"; // <GPGSID>
        public const string achievement_welcome = "CgkIhaXbp9AHEAIQAQ"; // <GPGSID>
        public const string achievement_shopping_king = "CgkIhaXbp9AHEAIQCQ"; // <GPGSID>
        public const string achievement_glue_wallpaper = "CgkIhaXbp9AHEAIQBA"; // <GPGSID>
        public const string achievement_korea = "CgkIhaXbp9AHEAIQCA"; // <GPGSID>
        public const string achievement_hello_session_im_depressed = "CgkIhaXbp9AHEAIQDQ"; // <GPGSID>
        public const string achievement_fashion_is_my_profession = "CgkIhaXbp9AHEAIQAw"; // <GPGSID>
        public const string achievement_conqueror_of_the_top_of_the_rating = "CgkIhaXbp9AHEAIQBw"; // <GPGSID>
        public const string leaderboard_best_players = "CgkIhaXbp9AHEAIQAg"; // <GPGSID>
        public const string achievement_one_hour_of_wasted_time = "CgkIhaXbp9AHEAIQDA"; // <GPGSID>
        public const string achievement_beginner = "CgkIhaXbp9AHEAIQBQ"; // <GPGSID>

}

